spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_db
    username: treker_alfa
    password: 12345
    driver-class-name: org.postgresql.Driver
