spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/spotify_prod
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
