spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://prod-server:5432/spotify_db
    username: prod_user
    password: strong-password
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
