spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify_db
    username: treker_alfa
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update       # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  thymeleaf:
    cache: false

server:
  port: 8080
